
version: 2

sources:
    - name: cric_transform
      #For bigquery:
      #database: taxi-rides-ny-339813

      # For postgres:
      database: cric_data

      schema: public

      # loaded_at_field: record_loaded_at
      tables:
        - name: wickets
        - name: runs
         # freshness:
           # error_after: {count: 6, period: hour}
